language: go

os:
  - linux
  - osx

go:
  - 1.5.2

install:
  - make dependencies
  - test -z "$(go fmt ./...)"
  - make

script: make test && make test-long && make cover && make bench

sudo: false
