language: go

go:
  - 1.5.1

install:
  - make dependencies
  - test -z "$(go fmt ./...)"
  - golint ./modules/host
  - make

script: make test && make test-long && make cover && make bench

sudo: false
